# Generated by Django 4.2.29 on 2026-04-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_subcategory_experience_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
