# Generated by Django 4.2.29 on 2026-04-23 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experiences', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='total_reviews',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'experience')},
        ),
    ]
