# Generated by Django 4.2.29 on 2026-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='stars',
            field=models.IntegerField(choices=[(1, '1 Star - ★☆☆☆☆'), (2, '2 Stars - ★★☆☆☆'), (3, '3 Stars - ★★★☆☆'), (4, '4 Stars - ★★★★☆'), (5, '5 Stars - ★★★★★')], default=5),
        ),
    ]
