# Generated by Django 4.2.29 on 2026-04-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_testimonial_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.TextField(max_length=200),
        ),
    ]
