# Generated by Django 4.2.29 on 2026-04-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
